name: Onetime Setup
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}.stridespace.com
      - name: Push result to Testspace server
        run: |
          testspace README.md{0}
        if: always()